modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/LlamaPalooza/issues"
license="MIT"

[[mods]]
modId="llamapalooza"
version="${file.jarVersion}"
displayName="LLamaPalooza"
displayURL="https://www.curseforge.com/minecraft/mc-mods/llamapalooza"
authors="Mrbysco, ShyNieke"
description='''
Llama, llama, llama!
'''
[[dependencies.llamapalooza]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.llamapalooza]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"